### ISSUE TITLE
Will Py2C be compatible with other Python-to-C++ converters

### ISSUE THREAD

**Issue by jarble** [pradyunsg/Py2C#12]
One of the stated goals of Py2C is to translate Python into readable C++ code, which can be done automatically by the [Shedskin](https://code.google.com/p/shedskin/) and [Nuitka](http://nuitka.net/) compilers. Will Py2C be compatible with either of these compilers?

**Comment by pradyunsg** [comment]
The code generated is meant to be independent of the Python interpreter. While we may have a wrapper generated, it will be for interfacing/calling from Python, not running the code.

I'm not sure what you mean by compatible with the code generated by Shedskin and Nuitka.

**Comment by jarble** [comment]
The Nuitka compiler seems to be relatively complete now. Will Nuitka and Py2C be merged into one project (since they both translate Python source code into C++ code)?

**Comment by pradyunsg** [comment]
It is **very** premature for me to make any such comments/promises. Currently, Py2C is not even capable of compiling Hello World. So, it's going to hard to say where the code is headed or where it will end up.

Closing this issue.
